const PROVIDERS = [
  {
    id: 'opencode-zen',
    label: 'OpenCode Zen',
    baseUrl: 'https://opencode.ai',
    chatPath: '/zen/v1/chat/completions',
    model: 'minimax/minimax-2.5-chat',
  },
  {
    id: 'openrouter',
    label: 'OpenRouter',
    baseUrl: 'https://openrouter.ai',
    chatPath: '/api/v1/chat/completions',
    model: 'openai/gpt-4o-mini',
  },
  {
    id: 'openai',
    label: 'OpenAI',
    baseUrl: 'https://api.openai.com',
    chatPath: '/v1/chat/completions',
    model: 'gpt-4o-mini',
  },
  {
    id: 'groq',
    label: 'Groq',
    baseUrl: 'https://api.groq.com',
    chatPath: '/openai/v1/chat/completions',
    model: 'llama-3.3-70b-versatile',
  },
  {
    id: 'together',
    label: 'Together AI',
    baseUrl: 'https://api.together.xyz',
    chatPath: '/v1/chat/completions',
    model: 'meta-llama/Llama-3.3-70B-Instruct-Turbo',
  },
  {
    id: 'fireworks',
    label: 'Fireworks AI',
    baseUrl: 'https://api.fireworks.ai',
    chatPath: '/inference/v1/chat/completions',
    model: 'accounts/fireworks/models/llama-v3p1-70b-instruct',
  },
  {
    id: 'mistral',
    label: 'Mistral',
    baseUrl: 'https://api.mistral.ai',
    chatPath: '/v1/chat/completions',
    model: 'mistral-small-latest',
  },
  {
    id: 'xai',
    label: 'xAI',
    baseUrl: 'https://api.x.ai',
    chatPath: '/v1/chat/completions',
    model: 'grok-2-latest',
  },
  {
    id: 'deepinfra',
    label: 'DeepInfra',
    baseUrl: 'https://api.deepinfra.com',
    chatPath: '/v1/openai/chat/completions',
    model: 'meta-llama/Meta-Llama-3.3-70B-Instruct',
  },
  {
    id: 'perplexity',
    label: 'Perplexity',
    baseUrl: 'https://api.perplexity.ai',
    chatPath: '/chat/completions',
    model: 'sonar',
  },
  {
    id: 'nvidia-nim',
    label: 'NVIDIA NIM',
    baseUrl: 'https://integrate.api.nvidia.com',
    chatPath: '/v1/chat/completions',
    model: 'meta/llama-3.1-70b-instruct',
  },
  {
    id: 'cerebras',
    label: 'Cerebras',
    baseUrl: 'https://api.cerebras.ai',
    chatPath: '/v1/chat/completions',
    model: 'llama-3.3-70b',
  },
  {
    id: 'sambanova',
    label: 'SambaNova',
    baseUrl: 'https://api.sambanova.ai',
    chatPath: '/v1/chat/completions',
    model: 'Meta-Llama-3.1-70B-Instruct',
  },
  {
    id: 'anyscale',
    label: 'Anyscale Endpoints',
    baseUrl: 'https://api.endpoints.anyscale.com',
    chatPath: '/v1/chat/completions',
    model: 'meta-llama/Llama-3.1-70B-Instruct',
  },
  {
    id: 'deepseek',
    label: 'DeepSeek',
    baseUrl: 'https://api.deepseek.com',
    chatPath: '/v1/chat/completions',
    model: 'deepseek-chat',
  },
  {
    id: 'moonshot',
    label: 'Moonshot AI',
    baseUrl: 'https://api.moonshot.ai',
    chatPath: '/v1/chat/completions',
    model: 'moonshot-v1-8k',
  },
  {
    id: '01ai',
    label: '01.AI',
    baseUrl: 'https://api.lingyiwanwu.com',
    chatPath: '/v1/chat/completions',
    model: 'yi-large',
  },
  {
    id: 'hyperbolic',
    label: 'Hyperbolic',
    baseUrl: 'https://api.hyperbolic.xyz',
    chatPath: '/v1/chat/completions',
    model: 'meta-llama/Meta-Llama-3.1-70B-Instruct',
  },
  {
    id: 'novita',
    label: 'Novita AI',
    baseUrl: 'https://api.novita.ai',
    chatPath: '/v3/openai/chat/completions',
    model: 'meta-llama/llama-3.1-70b-instruct',
  },
  {
    id: 'siliconflow',
    label: 'SiliconFlow',
    baseUrl: 'https://api.siliconflow.cn',
    chatPath: '/v1/chat/completions',
    model: 'Qwen/Qwen2.5-72B-Instruct',
  },
  {
    id: 'inference-net',
    label: 'Inference.net',
    baseUrl: 'https://api.inference.net',
    chatPath: '/v1/chat/completions',
    model: 'meta-llama/Meta-Llama-3.1-70B-Instruct',
  },
  {
    id: 'friendli',
    label: 'FriendliAI',
    baseUrl: 'https://api.friendli.ai',
    chatPath: '/dedicated/v1/chat/completions',
    model: 'meta-llama-3.1-70b-instruct',
  },
  {
    id: 'ollama',
    label: 'Ollama (local)',
    baseUrl: 'http://localhost:11434',
    chatPath: '/v1/chat/completions',
    model: 'llama3.3',
    local: true,
  },
  {
    id: 'lmstudio',
    label: 'LM Studio (local)',
    baseUrl: 'http://localhost:1234',
    chatPath: '/v1/chat/completions',
    model: 'local-model',
    local: true,
  },
  {
    id: 'jan',
    label: 'Jan (local)',
    baseUrl: 'http://localhost:1337',
    chatPath: '/v1/chat/completions',
    model: 'local-model',
    local: true,
  },
  {
    id: 'llamacpp',
    label: 'llama.cpp server (local)',
    baseUrl: 'http://localhost:8080',
    chatPath: '/v1/chat/completions',
    model: 'local-model',
    local: true,
  },
  {
    id: 'vllm',
    label: 'vLLM (local/remote)',
    baseUrl: 'http://localhost:8000',
    chatPath: '/v1/chat/completions',
    model: 'local-model',
    local: true,
  },
  {
    id: 'custom',
    label: 'Custom OpenAI-compatible endpoint',
    baseUrl: '',
    chatPath: '',
    model: 'gpt-4o-mini',
    requiresEndpointInput: true,
  },
  {
    id: 'modal-custom',
    label: 'Modal deployment (custom URL)',
    baseUrl: '',
    chatPath: '',
    model: 'your-modal-model',
    requiresEndpointInput: true,
  },
];

function getProviderById(id) {
  return PROVIDERS.find((p) => p.id === id) || null;
}

module.exports = {
  PROVIDERS,
  getProviderById,
};
