const PROVIDERS = [
  {
    id: 'claude-web',
    label: 'Claude.ai (Free)',
    baseUrl: 'https://claude.ai',
    chatPath: '/api/organizations',
    model: 'claude-sonnet-4-5',
    requiresApiKey: false,
    apiKeyUrl: 'https://claude.ai',
    note: 'Uses your claude.ai browser session — no API key needed',
  },
  {
    id: 'opencode-zen',
    label: 'OpenCode Zen',
    baseUrl: 'https://opencode.ai',
    chatPath: '/zen/v1/chat/completions',
    model: 'minimax/minimax-2.5-chat',
    requiresApiKey: true,
    apiKeyUrl: 'https://opencode.ai/dashboard',
  },
  {
    id: 'github-copilot',
    label: 'GitHub Copilot',
    baseUrl: 'https://api.githubcopilot.com',
    chatPath: '/chat/completions',
    model: 'gpt-4o',
    requiresApiKey: true,
    apiKeyUrl: 'https://github.com/settings/copilot',
  },
  {
    id: 'openrouter',
    label: 'OpenRouter',
    baseUrl: 'https://openrouter.ai',
    chatPath: '/api/v1/chat/completions',
    model: 'openai/gpt-4o-mini',
    requiresApiKey: true,
    apiKeyUrl: 'https://openrouter.ai/keys',
  },
  {
    id: 'openai',
    label: 'OpenAI',
    baseUrl: 'https://api.openai.com',
    chatPath: '/v1/chat/completions',
    model: 'gpt-4o-mini',
    requiresApiKey: true,
    apiKeyUrl: 'https://platform.openai.com/api-keys',
  },
  {
    id: 'groq',
    label: 'Groq',
    baseUrl: 'https://api.groq.com',
    chatPath: '/openai/v1/chat/completions',
    model: 'llama-3.3-70b-versatile',
    requiresApiKey: true,
    apiKeyUrl: 'https://console.groq.com/keys',
  },
  {
    id: 'together',
    label: 'Together AI',
    baseUrl: 'https://api.together.xyz',
    chatPath: '/v1/chat/completions',
    model: 'meta-llama/Llama-3.3-70B-Instruct-Turbo',
    requiresApiKey: true,
    apiKeyUrl: 'https://api.together.xyz/settings/api-keys',
  },
  {
    id: 'fireworks',
    label: 'Fireworks AI',
    baseUrl: 'https://api.fireworks.ai',
    chatPath: '/inference/v1/chat/completions',
    model: 'accounts/fireworks/models/llama-v3p1-70b-instruct',
    requiresApiKey: true,
    apiKeyUrl: 'https://fireworks.ai/account/api-keys',
  },
  {
    id: 'mistral',
    label: 'Mistral',
    baseUrl: 'https://api.mistral.ai',
    chatPath: '/v1/chat/completions',
    model: 'mistral-small-latest',
    requiresApiKey: true,
    apiKeyUrl: 'https://console.mistral.ai/api-keys',
  },
  {
    id: 'xai',
    label: 'xAI',
    baseUrl: 'https://api.x.ai',
    chatPath: '/v1/chat/completions',
    model: 'grok-2-latest',
    requiresApiKey: true,
    apiKeyUrl: 'https://console.x.ai',
  },
  {
    id: 'deepinfra',
    label: 'DeepInfra',
    baseUrl: 'https://api.deepinfra.com',
    chatPath: '/v1/openai/chat/completions',
    model: 'meta-llama/Meta-Llama-3.3-70B-Instruct',
    requiresApiKey: true,
    apiKeyUrl: 'https://deepinfra.com/dash/api_keys',
  },
  {
    id: 'perplexity',
    label: 'Perplexity',
    baseUrl: 'https://api.perplexity.ai',
    chatPath: '/chat/completions',
    model: 'sonar',
    requiresApiKey: true,
    apiKeyUrl: 'https://www.perplexity.ai/settings/api',
  },
  {
    id: 'nvidia-nim',
    label: 'NVIDIA NIM',
    baseUrl: 'https://integrate.api.nvidia.com',
    chatPath: '/v1/chat/completions',
    model: 'meta/llama-3.1-70b-instruct',
    requiresApiKey: true,
    apiKeyUrl: 'https://build.nvidia.com/explore/discover',
  },
  {
    id: 'cerebras',
    label: 'Cerebras',
    baseUrl: 'https://api.cerebras.ai',
    chatPath: '/v1/chat/completions',
    model: 'llama-3.3-70b',
    requiresApiKey: true,
    apiKeyUrl: 'https://cloud.cerebras.ai/platform/',
  },
  {
    id: 'sambanova',
    label: 'SambaNova',
    baseUrl: 'https://api.sambanova.ai',
    chatPath: '/v1/chat/completions',
    model: 'Meta-Llama-3.1-70B-Instruct',
    requiresApiKey: true,
    apiKeyUrl: 'https://cloud.sambanova.ai/apis',
  },
  {
    id: 'anyscale',
    label: 'Anyscale Endpoints',
    baseUrl: 'https://api.endpoints.anyscale.com',
    chatPath: '/v1/chat/completions',
    model: 'meta-llama/Llama-3.1-70B-Instruct',
    requiresApiKey: true,
    apiKeyUrl: 'https://console.anyscale.com/o/default/configurations/app-config',
  },
  {
    id: 'deepseek',
    label: 'DeepSeek',
    baseUrl: 'https://api.deepseek.com',
    chatPath: '/v1/chat/completions',
    model: 'deepseek-chat',
    supportsReasoning: true,
    requiresApiKey: true,
    apiKeyUrl: 'https://platform.deepseek.com/api_keys',
  },
  {
    id: 'moonshot',
    label: 'Moonshot AI',
    baseUrl: 'https://api.moonshot.ai',
    chatPath: '/v1/chat/completions',
    model: 'moonshot-v1-8k',
    supportsReasoning: true,
    requiresApiKey: true,
    apiKeyUrl: 'https://platform.moonshot.cn/console/api-keys',
  },
  {
    id: '01ai',
    label: '01.AI',
    baseUrl: 'https://api.lingyiwanwu.com',
    chatPath: '/v1/chat/completions',
    model: 'yi-large',
    requiresApiKey: true,
    apiKeyUrl: 'https://platform.lingyiwanwu.com/apikeys',
  },
  {
    id: 'hyperbolic',
    label: 'Hyperbolic',
    baseUrl: 'https://api.hyperbolic.xyz',
    chatPath: '/v1/chat/completions',
    model: 'meta-llama/Meta-Llama-3.1-70B-Instruct',
    requiresApiKey: true,
    apiKeyUrl: 'https://app.hyperbolic.xyz/settings/api-keys',
  },
  {
    id: 'novita',
    label: 'Novita AI',
    baseUrl: 'https://api.novita.ai',
    chatPath: '/v3/openai/chat/completions',
    model: 'meta-llama/llama-3.1-70b-instruct',
    requiresApiKey: true,
    apiKeyUrl: 'https://novita.ai/dashboard/key',
  },
  {
    id: 'siliconflow',
    label: 'SiliconFlow',
    baseUrl: 'https://api.siliconflow.cn',
    chatPath: '/v1/chat/completions',
    model: 'Qwen/Qwen2.5-72B-Instruct',
    supportsReasoning: true,
    requiresApiKey: true,
    apiKeyUrl: 'https://cloud.siliconflow.cn/account/ak',
  },
  {
    id: 'inference-net',
    label: 'Inference.net',
    baseUrl: 'https://api.inference.net',
    chatPath: '/v1/chat/completions',
    model: 'meta-llama/Meta-Llama-3.1-70B-Instruct',
    requiresApiKey: true,
    apiKeyUrl: 'https://inference.net/',
  },
  {
    id: 'friendli',
    label: 'FriendliAI',
    baseUrl: 'https://api.friendli.ai',
    chatPath: '/dedicated/v1/chat/completions',
    model: 'meta-llama-3.1-70b-instruct',
    requiresApiKey: true,
    apiKeyUrl: 'https://suite.friendli.ai/user-settings/tokens',
  },
  {
    id: 'ollama',
    label: 'Ollama (local)',
    baseUrl: 'http://localhost:11434',
    chatPath: '/v1/chat/completions',
    model: 'llama3.3',
    local: true,
    requiresApiKey: false,
  },
  {
    id: 'lmstudio',
    label: 'LM Studio (local)',
    baseUrl: 'http://localhost:1234',
    chatPath: '/v1/chat/completions',
    model: 'local-model',
    local: true,
    requiresApiKey: false,
  },
  {
    id: 'jan',
    label: 'Jan (local)',
    baseUrl: 'http://localhost:1337',
    chatPath: '/v1/chat/completions',
    model: 'local-model',
    local: true,
    requiresApiKey: false,
  },
  {
    id: 'llamacpp',
    label: 'llama.cpp server (local)',
    baseUrl: 'http://localhost:8080',
    chatPath: '/v1/chat/completions',
    model: 'local-model',
    local: true,
    requiresApiKey: false,
  },
  {
    id: 'vllm',
    label: 'vLLM (local/remote)',
    baseUrl: 'http://localhost:8000',
    chatPath: '/v1/chat/completions',
    model: 'local-model',
    local: true,
    requiresApiKey: false,
  },
  {
    id: 'custom',
    label: 'Custom OpenAI-compatible endpoint',
    baseUrl: '',
    chatPath: '',
    model: 'gpt-4o-mini',
    requiresEndpointInput: true,
    requiresApiKey: true,
  },
  {
    id: 'modal-custom',
    label: 'Modal deployment (custom URL)',
    baseUrl: '',
    chatPath: '',
    model: 'your-modal-model',
    requiresEndpointInput: true,
    requiresApiKey: true,
  },
];
const getProviderById = (id) => PROVIDERS.find((p) => p.id === id) || null;
module.exports = { PROVIDERS, getProviderById };
